Models/Song.cs
namespace MusicStore.Models
{
    public class Song
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Singer { get; set; }
        public Language Language { get; set; }
        public int LanguageId { get; set; }
    }
}

Controllers/SongController.cs
using System.Collections.Generic;
using AutoMapper;
using ClientNotifications;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MusicStore.Models;
using MusicStore.Repository;
using static ClientNotifications.Helpers.NotificationHelper;

namespace MusicStore.Controllers
{
    public class SongController : Controller
    {
        private ISongRepository _songRepository;
        private ILanguageRepository _languageRepository;
        private IClientNotification _clientNotification;
        private IMapper _mapper;
        public SongController(ISongRepository songRepository,
                            ILanguageRepository languageRepository,
                            IClientNotification clientNotification,
                            IMapper mapper)
        {
            _songRepository = songRepository;
            _languageRepository = languageRepository;
            _clientNotification = clientNotification;
            _mapper = mapper;
        }

        public IActionResult Index(int LanguageId=0)
        {
            var songs = new List<Song>();
            if(LanguageId==0){
                songs = _songRepository.GetAllSongs();
            }else
            {
                songs = _songRepository.GetSongByLanguage(LanguageId);
            }
            var languages = _songRepository.GetSongLanguage();
            ViewBag.songLanguage = new SelectList(languages, nameof(Language.Id), nameof(Language.Name));
           return View(songs);          
        }
        [HttpGet]
        public IActionResult New()
        {
            var songvm = new SongVm();
            songvm.IsEditMode = "false";

            var languages = _songRepository.GetSongLanguage();
            ViewBag.songLanguage = new SelectList(languages, nameof(Language.Id), nameof(Language.Name));
            return View(songvm);
        }
        [HttpPost]
        public IActionResult New(SongVm songvm)
        {
            var song = _mapper.Map<Song>(songvm);

            if(songvm.IsEditMode.Equals("false")){
                _songRepository.Create(song);
                _clientNotification.AddToastNotification("New Song Created",
                                            NotificationType.success,
                                            null);
            }else
            {
                _songRepository.Update(song);
                _clientNotification.AddToastNotification("Song Updated",
                                            NotificationType.success,
                                            null);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int Id)
        {
            var songs = _songRepository.GetSingleSong(Id);

            var songVm = _mapper.Map<SongVm>(songs);

            songVm.IsEditMode="true";

            var languages = _songRepository.GetSongLanguage();
            ViewBag.songLanguage = new SelectList(languages, nameof(Language.Id), nameof(Language.Name));

            return View("New",songVm);
        }
        public IActionResult Delete(int Id)
        {
            var song = _songRepository.GetSingleSong(Id);
            _songRepository.Delete(song);
            _clientNotification.AddToastNotification("Succesfully Deleted",
                                            NotificationType.success,
                                            null);
            return RedirectToAction("Index");
        }
    }
}

Views/Song/Index.cshtml
@model List<Song>

<h2>All Songs</h2>
<form asp-action="Index" asp-controller="Song" method="post"> 
    <select name="LanguageId" asp-items="@ViewBag.songLanguage">
        <option value="">Select Language </option>
    </select>

    <button type="submit" class="btn btn-primary">Go</button>
</form>    

<div class="row">
    @foreach(Song songs in Model) {
        <div class="panel panel-info col-sm-4">
            <div class="panel-heading">
                Song Name: @songs.Name
            </div>
            <div class="panel-body">
                <p>Song Language: @songs.Language.Name</p>
                <p>Singer: @songs.Singer</p>
            </div>
            <div class="panel-footer">
                <a asp-action="Edit" 
                    asp-controller="Song" 
                    asp-route-Id="@songs.Id" 
                    class="btn btn-info">Edit
                </a>
                <a asp-action="Delete" 
                    asp-controller="Song" 
                    asp-route-Id="@songs.Id" 
                    class="btn btn-danger">Delete
                </a>
            </div>      
        </div>
    }
</div> 

Views/Song/New.cshtml
@model SongVm

<h2>Songs</h2>

<form asp-action="New" asp-controller="Song" method="post">

    <input hidden asp-for="@Model.Id"/>
    <input hidden asp-for="@Model.IsEditMode"/>

    <select asp-for="LanguageId" asp-items="@ViewBag.songLanguage">
        <option value="">Select Language </option>
    </select>

    <label asp-for="@Model.Name"></label>
    <input asp-for="@Model.Name"/>

    <div>
        <input type ="radio" asp-for="Singer" checked="checked" value="Eid seran">
        <label for="singer">Eid seran</label>

        <input type ="radio" asp-for="Singer" value="Anu malik">
        <label for="singer">Anu malik</label>

        <input type ="radio" asp-for="Singer" value="Raju Lama">
        <label for="singer">Raju Lama</label>
    </div>

    <button class="btn btn-primary" type="submit">save</button>

</form>